@baseUrl = http://localhost:5000

GET {{baseUrl}}/users?username=hieu123

###

POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Minh Hieu Duong",
  "mail": "hieu.abc@gmail.com",
  "phone": "0989898989",
  "username": "hieu123",
  "password": "123456"
}
